config/routes.rb
XboxGetOne::Application.routes.draw do
  resources :users

  resources :checkers

  root :to => 'checkers#index'

end

app/models/checker.rb
class Checker < ActiveRecord::Base
	
  attr_accessible :item, :name, :site, :url, :positive_selector, :positive_response,
  								:negative_response, :negative_selector, :item_status
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/checkers_controller.rb
class CheckersController < ApplicationController
  # GET /checkers
  # GET /checkers.json
  require 'nokogiri'
  require 'open-uri'

  def index
    @checkers = Checker.all

    @checkers.each do |checker|
      old_status = checker.item_status
      doc = Nokogiri::HTML(open(checker.url))
      if doc.at_css(checker.positive_selector).present? == true || doc.at_css(checker.negative_selector).present? == false
        doc.at_css(checker.positive_selector).text
        unless old_status == true
          UserMailer.xbox_is_at(User.first, checker, Time.now).deliver
          checker.item_status = true
        end
      else
        unless old_status == false
          UserMailer.xbox_out_at(User.first, checker, Time.now).deliver
          checker.item_status = false
        end
      end
      checker.save
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkers }
    end
  end

  # GET /checkers/1
  # GET /checkers/1.json
  def show
    @checker = Checker.find(params[:id])
    #

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checker }
    end
  end

  # GET /checkers/new
  # GET /checkers/new.json
  def new
    @checker = Checker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checker }
    end
  end

  # GET /checkers/1/edit
  def edit
    @checker = Checker.find(params[:id])
  end

  # POST /checkers
  # POST /checkers.json
  def create
    @checker = Checker.new(params[:checker])

    respond_to do |format|
      if @checker.save
        format.html { redirect_to @checker, notice: 'Checker was successfully created.' }
        format.json { render json: @checker, status: :created, location: @checker }
      else
        format.html { render action: "new" }
        format.json { render json: @checker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checkers/1
  # PUT /checkers/1.json
  def update
    @checker = Checker.find(params[:id])

    respond_to do |format|
      if @checker.update_attributes(params[:checker])
        format.html { redirect_to @checker, notice: 'Checker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkers/1
  # DELETE /checkers/1.json
  def destroy
    @checker = Checker.find(params[:id])
    @checker.destroy

    respond_to do |format|
      format.html { redirect_to checkers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkers_helper.rb
module CheckersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkers/_form.html.erb
<%= form_for(@checker) do |f| %>
  <% if @checker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checker.errors.count, "error") %> prohibited this checker from being saved:</h2>

      <ul>
      <% @checker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site %><br />
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :positive_selector %><br />
    <%= f.text_field :positive_selector %>
  </div>
  <div class="field">
    <%= f.label :positive_response %><br />
    <%= f.text_field :positive_response %>
  </div>
  <div class="field">
    <%= f.label :negative_selector %><br />
    <%= f.text_field :negative_selector %>
  </div>
  <div class="field">
    <%= f.label :negative_response %><br />
    <%= f.text_field :negative_response %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkers/edit.html.erb
<h1>Editing checker</h1>

<%= render 'form' %>

<%= link_to 'Show', @checker %> |
<%= link_to 'Back', checkers_path %>

app/views/checkers/index.html.erb
<h1>Listing checkers</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Site</th>
    <th>Url</th>
    <th>Item</th>
    <th>item_status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checkers.each do |checker| %>
  <% doc = Nokogiri::HTML(open(checker.url)) %>
  <tr>
    <td><%= checker.name %></td>
    <td><%= checker.site %></td>
    <td><%= link_to "URL", checker.url, :target => '_blank' %></td>
    <td><%= checker.item %></td>
    <td><%= checker.item_status ? "IN STOCK" : "not in stock" %></td>
    <td><%= link_to 'Show', checker %></td>
    <td><%= link_to 'Edit', edit_checker_path(checker) %></td>
    <td><%= link_to 'Destroy', checker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Checker', new_checker_path %>

<div id="script_area">
  <script>

    setInterval(function() {
      $.ajax({
        
          url: '/checkers'
      })
    }, 60000);

  </script>
</div>

app/views/checkers/new.html.erb
<h1>New checker</h1>

<%= render 'form' %>

<%= link_to 'Back', checkers_path %>

app/views/checkers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @checker.name %>
</p>

<p>
  <b>Site:</b>
  <%= @checker.site %>
</p>

<p>
  <b>Url:</b>
  <%= @checker.url %>
</p>

<p>
  <b>Item:</b>
  <%= @checker.item %>
</p>

<p>
  <b>Positive Selector:</b>
  <%= @checker.positive_selector %>
</p>

<p>
  <b>Positive Response:</b>
  <%= @checker.positive_response %>
</p>

<p>
  <b>Negative Selector:</b>
  <%= @checker.negative_selector %>
</p>

<p>
  <b>Negative Response:</b>
  <%= @checker.negative_response %>
</p>


<%= link_to 'Edit', edit_checker_path(@checker) %> |
<%= link_to 'Back', checkers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XboxGetOne</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>